version: "3.7"

services:
  app:
    build:
      context: .
      target: develop
    image: tikhoplav/gofile:dev
    volumes:
      - ./src:/src
      - ./pkg:/go/pkg
      - ./tmp:/tmp
    ports:
      - 80:80